FROM python:3
WORKDIR /app
ADD . /app

ENV PORT 8080
RUN pip install -r requirements.txt

RUN apt-get --fix-missing update && apt-get --fix-broken install && apt-get install -y poppler-utils && apt-get install -y tesseract-ocr && \
    apt-get install -y libtesseract-dev && apt-get install -y libleptonica-dev && ldconfig && apt-get install -y python3.6 && \
    apt-get install -y python3-pip && apt install -y libsm6 libxext6

RUN pip install Flask gunicorn
EXPOSE 80

CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 app:app
